version: '3.8'
services:
  app:
    build: .
    #volumes:
    #  - .:/app
    ports:
      - "8080:8080" # 必要に応じて使用するポートに合わせて変更してください
 # test:
 #   build: .
    #volumes:
    #  - .:/app
 #   command: go test ./character/

